// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: enquiry.proto

package enquiry

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainNumber string `protobuf:"bytes,1,opt,name=trainNumber,proto3" json:"trainNumber,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enquiry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_enquiry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_enquiry_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetTrainNumber() string {
	if x != nil {
		return x.TrainNumber
	}
	return ""
}

type TrainSchedule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StationName string `protobuf:"bytes,1,opt,name=stationName,proto3" json:"stationName,omitempty"`
	Arrival     string `protobuf:"bytes,2,opt,name=arrival,proto3" json:"arrival,omitempty"`
	Departure   string `protobuf:"bytes,3,opt,name=departure,proto3" json:"departure,omitempty"`
}

func (x *TrainSchedule) Reset() {
	*x = TrainSchedule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enquiry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainSchedule) ProtoMessage() {}

func (x *TrainSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_enquiry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainSchedule.ProtoReflect.Descriptor instead.
func (*TrainSchedule) Descriptor() ([]byte, []int) {
	return file_enquiry_proto_rawDescGZIP(), []int{1}
}

func (x *TrainSchedule) GetStationName() string {
	if x != nil {
		return x.StationName
	}
	return ""
}

func (x *TrainSchedule) GetArrival() string {
	if x != nil {
		return x.Arrival
	}
	return ""
}

func (x *TrainSchedule) GetDeparture() string {
	if x != nil {
		return x.Departure
	}
	return ""
}

type EnquiryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp []*TrainSchedule `protobuf:"bytes,1,rep,name=resp,proto3" json:"resp,omitempty"`
}

func (x *EnquiryResponse) Reset() {
	*x = EnquiryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enquiry_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnquiryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnquiryResponse) ProtoMessage() {}

func (x *EnquiryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enquiry_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnquiryResponse.ProtoReflect.Descriptor instead.
func (*EnquiryResponse) Descriptor() ([]byte, []int) {
	return file_enquiry_proto_rawDescGZIP(), []int{2}
}

func (x *EnquiryResponse) GetResp() []*TrainSchedule {
	if x != nil {
		return x.Resp
	}
	return nil
}

var File_enquiry_proto protoreflect.FileDescriptor

var file_enquiry_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x65, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x22, 0x2b, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x69, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x63,
	0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x72, 0x72, 0x69,
	0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x72, 0x72, 0x69, 0x76,
	0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65,
	0x22, 0x3d, 0x0a, 0x0f, 0x45, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x65, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x2e, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x32,
	0x51, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x42,
	0x0a, 0x12, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x12, 0x10, 0x2e, 0x65, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x18, 0x2e, 0x65, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79,
	0x2e, 0x45, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enquiry_proto_rawDescOnce sync.Once
	file_enquiry_proto_rawDescData = file_enquiry_proto_rawDesc
)

func file_enquiry_proto_rawDescGZIP() []byte {
	file_enquiry_proto_rawDescOnce.Do(func() {
		file_enquiry_proto_rawDescData = protoimpl.X.CompressGZIP(file_enquiry_proto_rawDescData)
	})
	return file_enquiry_proto_rawDescData
}

var file_enquiry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_enquiry_proto_goTypes = []interface{}{
	(*Message)(nil),         // 0: enquiry.Message
	(*TrainSchedule)(nil),   // 1: enquiry.TrainSchedule
	(*EnquiryResponse)(nil), // 2: enquiry.EnquiryResponse
}
var file_enquiry_proto_depIdxs = []int32{
	1, // 0: enquiry.EnquiryResponse.resp:type_name -> enquiry.TrainSchedule
	0, // 1: enquiry.TrainStatus.ReturnTrainDetails:input_type -> enquiry.Message
	2, // 2: enquiry.TrainStatus.ReturnTrainDetails:output_type -> enquiry.EnquiryResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_enquiry_proto_init() }
func file_enquiry_proto_init() {
	if File_enquiry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_enquiry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enquiry_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainSchedule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enquiry_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnquiryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enquiry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_enquiry_proto_goTypes,
		DependencyIndexes: file_enquiry_proto_depIdxs,
		MessageInfos:      file_enquiry_proto_msgTypes,
	}.Build()
	File_enquiry_proto = out.File
	file_enquiry_proto_rawDesc = nil
	file_enquiry_proto_goTypes = nil
	file_enquiry_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TrainStatusClient is the client API for TrainStatus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TrainStatusClient interface {
	ReturnTrainDetails(ctx context.Context, in *Message, opts ...grpc.CallOption) (*EnquiryResponse, error)
}

type trainStatusClient struct {
	cc grpc.ClientConnInterface
}

func NewTrainStatusClient(cc grpc.ClientConnInterface) TrainStatusClient {
	return &trainStatusClient{cc}
}

func (c *trainStatusClient) ReturnTrainDetails(ctx context.Context, in *Message, opts ...grpc.CallOption) (*EnquiryResponse, error) {
	out := new(EnquiryResponse)
	err := c.cc.Invoke(ctx, "/enquiry.TrainStatus/ReturnTrainDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrainStatusServer is the server API for TrainStatus service.
type TrainStatusServer interface {
	ReturnTrainDetails(context.Context, *Message) (*EnquiryResponse, error)
}

// UnimplementedTrainStatusServer can be embedded to have forward compatible implementations.
type UnimplementedTrainStatusServer struct {
}

func (*UnimplementedTrainStatusServer) ReturnTrainDetails(context.Context, *Message) (*EnquiryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnTrainDetails not implemented")
}

func RegisterTrainStatusServer(s *grpc.Server, srv TrainStatusServer) {
	s.RegisterService(&_TrainStatus_serviceDesc, srv)
}

func _TrainStatus_ReturnTrainDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainStatusServer).ReturnTrainDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/enquiry.TrainStatus/ReturnTrainDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainStatusServer).ReturnTrainDetails(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _TrainStatus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "enquiry.TrainStatus",
	HandlerType: (*TrainStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReturnTrainDetails",
			Handler:    _TrainStatus_ReturnTrainDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "enquiry.proto",
}
